# Neural Network Configuration

architecture: "Neural Network"          # Name of the network architecture

# Training Configuration
training:
  train_batch_size: 128        # Batch size for training
  test_batch_size: 64          # Batch size for training
  validation_batch_size: 64
  validation_percentage: 0.2
  loss_name: "CrossEntropyLoss"

optimizer:
  type: "Adam"
  lr: 0.001

scheduler_lr:
  type: "None"
  mode: 'min'
  factor: 0.1
  patience: 10
  verbose: False

# Data Configuration
data:
  train_dim: 50000
  test_dim: 10000
  input_dim: 784
  output_dim: 10

